### ISSUE TITLE
Let portal UI won't out of screen

### ISSUE THREAD

**Issue by NeoLSN** [fzyzcjy/flutter_portal#10]
This is a library which used flutter portal.
https://github.com/fayeed/flutter_mentions/issues/10

1) Can the flutter portal provide a way can let the portal UI always in the screen?
2) Or, let the portal UI be like a magnet in a case, just always around the main UI but won't follow the UI out of screen.

**Comment by magpiedigital** [comment]
Despite that mentioned issue having been resolved, I still think this would be an awesome addition. Not worrying if the portal will exceed the boundaries of the screen would be so useful.

**Comment by fzyzcjy** [comment]
Without further information, I will temporarily close this issue to make the issue tracker clean. Feel free to reopen (or create a new issue) if you are still facing problems after the #44 refactor!
