### ISSUE TITLE
Position of PortalEntry.child.

### ISSUE THREAD

**Issue by smiLLe** [fzyzcjy/flutter_portal#100]
Hi :)
I want to draw an Arrow on my Overvlay pointing to the button pressed. Is there anything that flutter_portals offers so that i can easily set the position of the arrow?

![image](https://user-images.githubusercontent.com/655296/228796770-f68b04e9-ac8e-4d87-9da9-060e8a64003d.png)

**Comment by fzyzcjy** [comment]
Maybe position your portal using left-top + with some offset. For example, say you know your arrow is at 16px, then offset by 16px

**Comment by smiLLe** [comment]
I also thought about that but what if the portal entry was to be positioned differently because if would be out of the portals bounds?

**Comment by fzyzcjy** [comment]
What bounds will it be out of? Your Portal is usually put at the top of tree

**Comment by smiLLe** [comment]
I will try a few more tests and update the issue.

**Comment by lvsecoto** [comment]
I also have this question.

If `shiftToWithinBound` is true, and the follower shifted, how can I get the offset?

Because I need the offset to align the follower's arrow align to the center of target widget...

**Comment by fzyzcjy** [comment]
Good question. What about this (just a draft): Use two portal targets - 

1. PortalTarget one - use  shiftToWithinBound, and draw a Card
2. PortalTarget two - do not use shiftToWithinBound, and draw an arrow
