### ISSUE TITLE
TextField and nested PortalTargets breaks app

### ISSUE THREAD

**Issue by namzug16** [fzyzcjy/flutter_portal#101]
**Describe the bug**
When putting a TextField or another PortalTarget inside a PortalTarget, the app will break and show the error

```"LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true."```

**To Reproduce**

IMPORTANT:
In order to reproduce the error correctly:
TextField: you need to be able to set the visibility of the PortalTarget (Look at example)
PortalTarget: you need to be able to set the visibility of this second PortalTarget

```dart
import 'package:flutter/material.dart';
import 'package:flutter_portal/flutter_portal.dart';

void main() => runApp(
      const Portal(
        child: MaterialApp(
          home: Material(
            child: PortalError(),
          ),
        ),
      ),
    );

class PortalError extends StatefulWidget {
  const PortalError({Key? key}) : super(key: key);

  @override
  State<PortalError> createState() => _PortalErrorState();
}

class _PortalErrorState extends State<PortalError> {
  bool isOpened = false;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: PortalTarget(
        visible: isOpened,
        anchor: const Aligned(
          follower: Alignment.topCenter,
          target: Alignment.bottomCenter,
        ),
        portalFollower: SizedBox(
          width: 400,
          height: 300,
          child: TextFormField(),
        ),
        child: TextButton(
          onPressed: () {
            setState(() {
              isOpened = !isOpened;
            });
          },
          child: const Text('PortalTarget'),
        ),
      ),
    );
  }
}
```
1.- Make the PortalTarget visible by pressing the button 
2.- Click on the TextField 

**The exception will be fired**

3.-Try to type inside the TextField, which will fire again the exception 
4.- When clicking on the TextField, the inserted text that was not visible, will be visible now

**Possible Origin**

When setting a couple of Breakpoints I realised one thing

On the function ```_debugCheckLeaderBeforeFollower()``` inside ```layer.dart```
<img width="696" alt="image" src="https://user-images.githubusercontent.com/77210010/236562683-dcdb12c0-14a9-427a-97cd-986b96ca4129.png">

The first iteration of the while loop fails because sibling does not have a next sibling

However when you checked the previous siblings of ```sibling```` you find as the second previous sibling ```followerSubtreeBelowAncestor```

<img width="997" alt="image" src="https://user-images.githubusercontent.com/77210010/236563635-4d3049ca-ba0d-478e-bdea-5a2091f550b5.png">

I tried to fix it myself but didn't have any results.

**Comment by fzyzcjy** [comment]
Hmm looks like a long-living bug: https://github.com/fzyzcjy/flutter_portal/issues/76

Firstly, have you tried the master branch?

Workaround: Maybe make the portal target always visible, and use things like `visible ? TextField() : Container()` to hide it (?)

**Comment by namzug16** [comment]
Yeah sorry, I forgot to mention #76 

Yeah I am using the master branch and I have tried the workaround too but the same error pops out

**Comment by davidsdearaujo** [comment]
Try to use this widget _(it replaces all the Portal structure)_ [[dartpad live example]](https://dartpad.dev/?id=f9643b849aa0a1503cdcf5685a39e4cf):

**overlay_button_builder.dart**
```dart
import 'package:flutter/material.dart';

class OverlayButtonBuilder extends StatefulWidget {
  final Widget child;
  final Widget overlay;
  final bool showOverlay;
  final OverlayAnchor anchor;
  const OverlayButtonBuilder({
    super.key,
    required this.child,
    required this.overlay,
    required this.showOverlay,
    this.anchor = OverlayAnchor.dropdown,
  });

  @override
  State<OverlayButtonBuilder> createState() => _OverlayButtonBuilderState();
}

class _OverlayButtonBuilderState extends State<OverlayButtonBuilder> {
  OverlayEntry? entry;
  final layerLink = LayerLink();

  @override
  void initState() {
    super.initState();
    applyVisibilityState();
  }

  @override
  void didUpdateWidget(covariant OverlayButtonBuilder oldWidget) {
    applyVisibilityState();
    super.didUpdateWidget(oldWidget);
  }

  @override
  Widget build(BuildContext context) {
    return CompositedTransformTarget(
      link: layerLink,
      child: widget.child,
    );
  }

  void applyVisibilityState() {
    final isShowOverlay = widget.showOverlay && entry == null;
    final isHideOverlay = !widget.showOverlay && entry != null;

    WidgetsBinding.instance.addPostFrameCallback((timer) {
      if (isShowOverlay) showOverlay();
      if (isHideOverlay) hideOverlay();
    });
  }

  void hideOverlay() {
    entry?.remove();
    entry = null;
  }

  void showOverlay() {
    if (entry != null) return;
    entry = OverlayEntry(
      opaque: false,
      builder: (context) => Material(
        type: MaterialType.transparency,
        child: Center(
          child: CompositedTransformFollower(
            link: layerLink,
            offset: widget.anchor.dialogOffset,
            followerAnchor: widget.anchor.dialog,
            targetAnchor: widget.anchor.button,
            child: widget.overlay,
          ),
        ),
      ),
    );
    Overlay.of(context).insert(entry!);
  }
}

class OverlayAnchor {
  final Alignment button;
  final Alignment dialog;
  final Offset dialogOffset;
  const OverlayAnchor({
    required this.button,
    required this.dialog,
    this.dialogOffset = Offset.zero,
  });

  static const dropdown = OverlayAnchor(
    button: Alignment.bottomRight,
    dialog: Alignment.topRight,
    dialogOffset: Offset(0, 8),
  );

  OverlayAnchor copyWith({
    Alignment? button,
    Alignment? dialog,
    Offset? dialogOffset,
  }) {
    return OverlayAnchor(
      button: button ?? this.button,
      dialog: dialog ?? this.dialog,
      dialogOffset: dialogOffset ?? this.dialogOffset,
    );
  }
}
```

**HOW TO USE**
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: HomeWidget()));
}

class HomeWidget extends StatefulWidget {
  const HomeWidget({super.key});

  @override
  State<HomeWidget> createState() => _HomeWidgetState();
}

class _HomeWidgetState extends State<HomeWidget> {
  bool showOverlay = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Page')),
      body: Center(
        child: OverlayButtonBuilder(
          showOverlay: showOverlay,
          anchor: const OverlayAnchor(
            button: Alignment.bottomRight,
            dialog: Alignment.topRight,
            dialogOffset: Offset(0, 8),
          ),
          overlay: Container(
            width: 250,
            color: Colors.amber,
            padding: const EdgeInsets.all(15),
            child: const TextField(),
          ),
          child: ElevatedButton(
            child: const Text('Click me to show/hide'),
            onPressed: () {
              setState(() {
                showOverlay = !showOverlay;
              });
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by bartosz-timecamp** [comment]
I encountered the same issue described here. I tried the suggested solutions mentioned in the issue thread, but the error still persists. Additionally, I made sure to have the latest version of the flutter_portal package. Please let me know if there are any updates or workarounds for this problem.

**Comment by fzyzcjy** [comment]
Well, this is a long living bug (and seems to be the only one reported in a long time). I am really out of bandwidth since I am busy with my app and open source projects, but feel free to examine it and create a PR! I am happy to provide suggestions about how to debug it: For example, the first step may be to dump the trees (render tree, layer tree etc) in a minimal reproducible sample.

**Comment by bartosz-timecamp** [comment]
I understand that running open source projects takes time. The main issue may be related to the TextField widget or its text rendering. I tried using CupertinoTextField, but encountered the same problem. Changing to EditableText was the only solution that worked. 

I will try to create PR with a sample project in the following week so that we can further investigate this issue.

**Comment by fzyzcjy** [comment]
> Changing to EditableText was the only solution that worked.

A guess: Then maybe it is the `Overlay` used inside TextField? Maybe try to hackily remove those OverlayEntry inside TextField (by temporarily modify flutter source code) and see whether it works?

**Comment by fzyzcjy** [comment]
> Yes, it is related to overlays which are used to draw selection controls.
It is impossible to remove them.

Btw, Does things like these work?
https://api.flutter.dev/flutter/material/TextField/selectionControls.html
https://api.flutter.dev/flutter/material/TextField/selectionEnabled.html

**Comment by SoichiroSatoDev** [comment]
It seems that wrapping the child with a Portal widget, rather than the MaterialApp itself, can avoid errors.
