### ISSUE TITLE
Relationship to OverlayPortal

### ISSUE THREAD

**Issue by jaween** [fzyzcjy/flutter_portal#104]
**Describe what scenario you think is uncovered by the existing examples/articles**
The Flutter SDK contains an [`OverlayPortal`](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html) widget which I believe was based on this package. I think it would be worthwhile to document the pros/cons of using the SDK widget versus this package.

For example, does this package include additional functionality that `OverlayPortal` does not? Or maybe something about how `OverlayPortal` recommends sticking with the imperative `OverlayEntry` when the child would not benefit from being in the subtree of the parent, is that recommendation also true of this package? 

**Describe why existing examples/articles do not cover this case**
The existing examples show what this package does and how to use it, and why to use it over `Overlay`/`OverlayEntry`, but not why to use it compared to`OverlayPortal`. I'm unable to find articles that mention the tradeoffs.

**Comment by fzyzcjy** [comment]
> The Flutter SDK contains an [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html) widget which I believe was based on this package.

Yes, the flutter built-in OverlayPortal is implemented in https://github.com/flutter/flutter/pull/105335, which is inspired by flutter_portal.

> I think it would be worthwhile to document the pros/cons of using the SDK widget versus this package.

Looks reasonable!

> For example, does this package include additional functionality that OverlayPortal does not? 

Without looking into details, a quick dump of my mind: flutter_portal is fully declarative, has flexiable anchor (e.g. you can alignToPortal and shiftToWithinBound).

> Or maybe something about how OverlayPortal recommends sticking with the imperative OverlayEntry when the child would not benefit from being in the subtree of the parent, is that recommendation also true of this package?

I will check that doc later; I personally use a ton of PortalTarget, which works good for me, and I have not seen problems.

Indeed I use it as an alternative to "z-index". You know, that need is really common.

**Comment by jaween** [comment]
Thank you, I appreciate the answers in your reply

And thank you guys for this package and getting something similar into the SDK

**Comment by fzyzcjy** [comment]
I checked OverlayPortal a bit more. It seems that OverlayPortal is similar to OverlayEntry except that:

> The main difference between [OverlayEntry](https://api.flutter.dev/flutter/widgets/OverlayEntry-class.html) and [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html) is that [OverlayEntry](https://api.flutter.dev/flutter/widgets/OverlayEntry-class.html) builds its widget subtree as a child of the target [Overlay](https://api.flutter.dev/flutter/widgets/Overlay-class.html), while [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html) uses [OverlayPortal.overlayChildBuilder](https://api.flutter.dev/flutter/widgets/OverlayPortal/overlayChildBuilder.html) to build a child widget of itself. This allows [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html)'s overlay child to depend on the same set of [InheritedWidget](https://api.flutter.dev/flutter/widgets/InheritedWidget-class.html)s as [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html), and it's also guaranteed that the overlay child will not outlive its [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html).
> On the other hand, [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html)'s implementation is more complex [...]

Therefore, the README here still applies, except for the Context-related lines there.
