### ISSUE TITLE
localToGlobal incorrect values at first paint

### ISSUE THREAD

**Issue by feduke-nukem** [fzyzcjy/flutter_portal#105]
**Describe the bug**
Probably `SingleChildScrollView` is causing this behaviour. `localToGlobal` returns wrong value at the very first paint of `RenderProxyBox`.

**To Reproduce**
[Repository](https://github.com/feduke-nukem/flutter_portal_global_to_local_issue_example)
See console output.

**Expected behavior**
Correct position at first frame of `RenderObject`

**Comment by fzyzcjy** [comment]
I see. The next step may be to move it to a widget test, and do some logging to see what's going wrong about computing the offsets.
