### ISSUE TITLE
PortalTarget bounds of gesture hit test

### ISSUE THREAD

**Issue by feduke-nukem** [fzyzcjy/flutter_portal#106]
**Describe the bug**
If the `PortalFollower` is outside the bounds of the child wrapped in Portal, it won't recognize any gestures, even if the follower is visible.

**To Reproduce**

[Repository](https://github.com/feduke-nukem/flutter_portal_target_follower_bounds_gesture_issue_example)

Select any element in the list by tapping on it, and a black rectangle will appear nearby. You should be able to tap it, and the index of the selected item will be printed to the console. Scroll the list so that the black rectangle is above the green container at the top, then tap on the black rectangle. Nothing happens.

**Expected behavior**
Gesture recognition should occur when tapping the visible widget.

**Comment by feduke-nukem** [comment]
It's ok

The problem is with my layout

**Comment by fzyzcjy** [comment]
Happy to see it is solved!
