### ISSUE TITLE
Pushing a route breaks animation inside portalFollower

### ISSUE THREAD

**Issue by Lootwig** [fzyzcjy/flutter_portal#107]
https://gist.github.com/Lootwig/71e32b14656ff7eb8b3c6538230e77cd

- Run the linked gist in a project with flutter_portal 1.1.4
- Tap the black rectangle. The letter "A" fades in and back out
- Tap the "push" button. A new route is pushed on the navigator
- Tap the black rectangle again. The letter "A" does not appear.

inserting a `print(_toggle)` into `A`'s build method shows that the value is set and reverted correctly, however, the animation only works when the initial route is active.

**Comment by fzyzcjy** [comment]
Firstly,

      onTap: () => setState(() {
        _toggle = !_toggle;
        Future.delayed(const Duration(seconds: 1), () {
          setState(() => _toggle = false);
        });
      }),

looks a bit incorrect. this may be better:

      onTap: () {
        setState(() { _toggle = true; });
        Future.delayed(const Duration(seconds: 1), () {
          setState(() => _toggle = false);
        });
      }

secondly, could you please further reduce the sample? for example, what happens if we make `A` non-clickable, but has a always-running animation (say, circular progress indicator), will its animation just halt?
