### ISSUE TITLE
Not clear how to use animations

### ISSUE THREAD

**Issue by Apollo108** [fzyzcjy/flutter_portal#110]
I tried to animate opacity for the portalFollower and used AnimatedOpacity without success until it worked with TweenAnimationBuilder as I noticed in one of your examples. Why it didn't work with AnimatedOpacity?

It may be helpful to describe it better in the docs.

Thank you for the awesome package!

**Comment by fzyzcjy** [comment]
> Why it didn't work with AnimatedOpacity?

IIRC things like that did work for me (but I do not remember exactly). Could you please show a minimal reproducible sample of the bug?

**Comment by Apollo108** [comment]
Sorry for the delay, I'll do this on the weekend)

**Comment by Apollo108** [comment]
With the clean example it's working, maybe my code somewhere is influencing it... Thank you, anyway)
