### ISSUE TITLE
`Semantics` does not work on two `nested` PortalTarget on web

### ISSUE THREAD

**Issue by dab246** [fzyzcjy/flutter_portal#115]
**Describe the bug**

- When I enable `Semantics` on the `Discovery` example, the `Plus` float button no longer increases the `counter` value, instead it closes the overlay.

**To Reproduce**

- Open the project example, edit the file [discovery.dart](https://github.com/fzyzcjy/flutter_portal/blob/master/example/lib/discovery.dart) to enable Semantics:
```dart
void main() {
    WidgetsFlutterBinding.ensureInitialized();
    SemanticsBinding.instance.ensureSemantics();
    runApp(const MyApp());
}
```
- Then run it on the web

https://github.com/user-attachments/assets/e2bf65ab-f58b-4943-a557-489e9cfcbd39

**Expected behavior**

- Plus floating button work fine.

**Comment by fzyzcjy** [comment]
Hmm, maybe we can debug by enabling the Flutter debug flags related to gesture events, and check what is different before/after the semantics is enabled.

**Comment by dab246** [comment]
> Hmm, maybe we can debug by enabling the Flutter debug flags related to gesture events, and check what is different before/after the semantics is enabled.

I have debugged but still can not find out what the problem is here. If possible, can you spend some time to research it for me. Thanks

**Comment by fzyzcjy** [comment]
I am really busy recently and maintaining https://github.com/fzyzcjy/flutter_rust_bridge also takes a lot of time... I will try to squeeze some time, but to be honest, may not be very recent...
