### ISSUE TITLE
Having trouble using a Portal inside of a Portal to recreate a 'Dialog' triggered from a 'Modal'

### ISSUE THREAD

**Issue by asteroid-studios** [fzyzcjy/flutter_portal#15]
I was having a lot of fun creating custom Datepickers and Dropdown buttons for myself, which work great.
Then I made a kind of modal/form which is also a PortalEntry, which works great.
But my problem is when I try to use one of my Datepickers/Dropdowns inside of my Pop up form, I get the following:

LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.
'package:flutter/src/rendering/layer.dart':

I assume this is because I am putting the PortalEntry inside of a portal, not a PortalEntry child. But I am struggling to find a workaround.

I tried putting another portalEntry in the form child and then passing the next portal I want when the corresponding button is clicked in the form. But the portal passed shows up underneath the form.

I tried even just showing a regular Dialog from the form. But it shows up underneath.

Would really appreciate any tips. Also just want to say, awesome plugin, allows for some really nice custom widgets

**Comment by rrousselGit** [comment]
Do you have some code example?

**Comment by asteroid-studios** [comment]
I quickly put something together to demonstrate, showing this error: 
**LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.
'package:flutter/src/rendering/layer.dart':
Failed assertion: line 2287 pos 12: 'link.leader!._lastOffset != null'**

``` dart
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:flutter_portal/flutter_portal.dart';

class ExampleDialog extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final dialogVisible = useState(false);

    return PortalEntry(
      visible: dialogVisible.value,
      portal: GestureDetector(
        onTap: () {
          dialogVisible.value = false;
        },
        child: Container(
          color: Colors.black12,
        ),
      ),
      child: PortalEntry(
        visible: dialogVisible.value,
        childAnchor: Alignment.bottomCenter,
        portalAnchor: Alignment.topCenter,
        portal: Container(
          padding: EdgeInsets.all(30),
          decoration: BoxDecoration(
            color: Colors.deepPurpleAccent,
            borderRadius: BorderRadius.circular(15),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              ExampleDatePicker(),
            ],
          ),
        ),
        child: RaisedButton(
          onPressed: () {
            dialogVisible.value = true;
          },
          child: Text('Show Dialog'),
        ),
      ),
    );
  }
}

class ExampleDatePicker extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final pickerVisible = useState(false);

    return PortalEntry(
      visible: pickerVisible.value,
      portal: GestureDetector(
        onTap: () {
          pickerVisible.value = false;
        },
        child: Container(
          color: Colors.black12,
        ),
      ),
      child: PortalEntry(
        visible: pickerVisible.value,
        childAnchor: Alignment.bottomCenter,
        portalAnchor: Alignment.topCenter,
        portal: Container(
          decoration: BoxDecoration(
            color: Colors.purpleAccent,
            borderRadius: BorderRadius.circular(15),
          ),
          child: Text(
              'DatePicker goes here but will always show behind the modal or not at all'),
        ),
        child: RaisedButton(
          onPressed: () {
            pickerVisible.value = true;
          },
          child: Text('Show DatePicker'),
        ),
      ),
    );
  }
}
```

If I remove the child and portal anchor of the datepicker, it just shows up behind the dialog so that doesnt work either

**Comment by AlexHartford** [comment]
I have a very similar issue, trying to use a portal dialog containing a portal dropdown. Same error, strangely enough, the error only occurs when trying to show the dropdown items, but if I manually set the dropdown items to show when the dialog is displayed, it renders without error.

**Comment by mugikhan** [comment]
Also, have the same issue creating a portal entry inside another portal entry.

**Comment by AlexHartford** [comment]
Any plans for this? I feel like it's not an uncommon use case

**Comment by rrousselGit** [comment]
I am aware of this bug but don't have the bandwidth to work on it at the moment

Feel free to open a pull request

**Comment by fzyzcjy** [comment]
Hi is there any updates? Or any hints - I am willing to make a fix

**Comment by fzyzcjy** [comment]
I guess it is the same reason as https://github.com/fzyzcjy/flutter_portal/issues/56.

Could you please have a try on master and see whether this bug exists? If so, feel free to reopen!
