### ISSUE TITLE
Allow the follower partially follow the target in selected axis; allow align relative to `Portal`

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_portal#17]
**Is your feature request related to a problem? Please describe.**

I have widget A (the red one in demo image) in my widget tree somewhere. Then I want to create widget B (blue one) by the following rules: Its `x` should be the width of screen. Its `y` should be the *same* as widget A (red one). 

I know how to **fully** follow another widget by using `PortalEntry`'s `childAnchor` and `portalAnchor`, but do not know how to do it **partially** only on one dimension.

Image illustrating my question (just Photoshoped it, not a screenshot):

[![enter image description here][1]][1]

Thanks very much!

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

  [1]: https://i.stack.imgur.com/kIYSq.png

**Comment by rrousselGit** [comment]
Hello!

Do you have a concrete example in mind rather than an abstract one?

**Comment by fzyzcjy** [comment]
@rrousselGit Yes. But the widget A and B are both very complex and unrelated to this question

**Comment by rrousselGit** [comment]
What about having the Overlay take the full width (but not height) , then use a padding/center to align it yourself?

**Comment by rrousselGit** [comment]
Like:

```dart
PortalEntry(
  entry: Container(height: 100, width: double.infinity, color: Colors.red),
  child:... 
)

**Comment by fzyzcjy** [comment]
Sounds great! I have thought about that, but never think of `width: double.infinity`. So it will automatically be clamped into the screen width?

**Comment by fzyzcjy** [comment]
Fixed.
