### ISSUE TITLE
Discovery example: rendering error in the FloatingActionButton

### ISSUE THREAD

**Issue by olof-dev** [fzyzcjy/flutter_portal#19]
**Describe the bug**
If I run `example/lib/discovery.dart`, the `FloatingActionButton` does not render correctly when the `PortalEntry` is visible: a tiny one is rendered on top of a genuine-sized one (and this one falls below the `Barrier`):

![PortalScreenshotNoDiscovery](https://user-images.githubusercontent.com/66305960/98561783-9506cb80-22a9-11eb-9bd6-8bb97ebd2887.png)

![PortalScreenshotWithDiscovery](https://user-images.githubusercontent.com/66305960/98561927-bc5d9880-22a9-11eb-83b1-4e617fd3f6b2.png)

**To Reproduce**
Run https://github.com/rrousselGit/flutter_portal/blob/master/example/lib/discovery.dart

**Expected behavior**
The `FloatingActionButton` should be displayed full size.

**Flutter version**
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (11 days ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3

**Comment by rrousselGit** [comment]
Could you share your environment?

**Comment by olof-dev** [comment]
Absolutely:

[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.3 at /home/xyz/code/flutter
    • Framework revision 8874f21e79 (11 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/xyz/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_272-8u272-b10-0ubuntu1~18.04-b10)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

**Comment by olof-dev** [comment]
p.s. I have verified that the small blue circle at the bottom right (in the center of the cut-out) is a genuine FAB -- one can click it.

**Comment by olof-dev** [comment]
It appears to have to do with the `Padding` around `child` in the `build()` method of `Discovery`. If I change the end value of the padding to 190 there instead of 200, i.e.

```dart
            CustomPaint(
              painter: HolePainter(Theme.of(context).accentColor),
              child: TweenAnimationBuilder<double>(
                duration: kThemeAnimationDuration,
                curve: Curves.easeOut,
                tween: Tween(begin: 50, end: visible ? 190 : 50),
                builder: (context, radius, _) {
                  return Padding(
                    padding: EdgeInsets.all(radius),
                    child: child,
                  );
                },
              ),
            ),
```
then I get the following:

![PortalReducedPadding](https://user-images.githubusercontent.com/66305960/98647540-4ef74980-2335-11eb-8d8d-a032c1b34cb8.png)

And with 175 instead of 190, the button renders normally.

**Comment by rrousselGit** [comment]
That is surprising because the button renders correctly for me.

**Comment by olof-dev** [comment]
Strange. I'm running the latest version on master, completely unmodified. If I increase the end padding of the tween to 250, the second copy of the FloatingActionButton is not visible at all. Do you see any difference if you replace the end padding of 
 the tween (currently 200) with 300, say?

**Comment by olof-dev** [comment]
Here's a couple of more screenshots, with debug paint enabled. In the first screenshot, the padding surrounding the FAB is finishing on 160 in the tween, and in the second one it is finishing at 190. I'd deleted the description ("Click to increment...") since it didn't appear to affect anything.

Looking at the source, I don't really understand the behaviour, and in particular what that top-left blue rectangle is. The reduced available space for the FAB seems to be synchronised with the width of that top-left rectangle reaching the width of the screen.

![PortalPadding160](https://user-images.githubusercontent.com/66305960/98679445-554eeb00-2360-11eb-8d8a-329a3ef5decf.png)
![PortalPadding190](https://user-images.githubusercontent.com/66305960/98679451-55e78180-2360-11eb-8985-5f45d46d47c4.png)

**Comment by stereotypeCoder** [comment]
Same issue here. I can see an overlay in top left corner which is also receives ontap event causing navigation issues in my app.

Is there any plan to work on it?

**Comment by rrousselGit** [comment]
Not in the near future

I have more important things to work on. But I'd be happy to review pull-requests

**Comment by stereotypeCoder** [comment]
@rrousselGit can I ask why is the area in the top right corner for so I can get some more context. Perhaps I can have a look and see if I can get it fixed for you. Cheers.

**Comment by rrousselGit** [comment]
Sorry for the late reply

I don't quite know what this square is. It'd need investigation
