### ISSUE TITLE
Visibility protection

### ISSUE THREAD

**Issue by biancashouse** [fzyzcjy/flutter_portal#24]
Consider your contextual menu example...

if you change the position of the button from Center to Align(alignment: bottomCenter...) then the menu appears 1/2 off screen.
would be very nice if it's position were corrected to ensure it is completely visible.

Really nice library, but for me that's a show stopper, because the anchor widget positions are not guaranteed to be away from the edge of the screen (e.g. on phones).

**Comment by biancashouse** [comment]
It is possible to get the size and position of the child if we provide a GlobalKey to it, right.
But in order to be able to adjust the Alignment values, we also need the size of the overlay (portal) widget.
Could you recommend a nice way to get that size ? Does it need to be rendered Offstage first ?

**Comment by fzyzcjy** [comment]
Hi, https://github.com/rrousselGit/flutter_portal/pull/44 is merged. Could you please check whether this issue is resolved :)

**Comment by fzyzcjy** [comment]
Without further information, I will temporarily close this issue to make the issue tracker clean. Feel free to reopen (or create a new issue) if you are still facing problems after the #44 refactor!

**Comment by Apollo108** [comment]
Hi, this doesn't work for me, the popup still goes behind the screen edge and is partially visible. Please, help me with this

**Comment by fzyzcjy** [comment]
Maybe try Aligned.shiftToWithinBound https://pub.dev/documentation/flutter_portal/latest/flutter_portal/Aligned-class.html

**Comment by Apollo108** [comment]
OMG, you saved my arse, thanks)

**Comment by fzyzcjy** [comment]
You are welcome!
