### ISSUE TITLE
Is there a way to position the Portal above all?

### ISSUE THREAD

**Issue by aytunch** [fzyzcjy/flutter_portal#25]
I need the overlay widget be on top of all other widgets in the app, no matter what navigator state the app is in.
I want to change the portal widget through provider
Is this possible, if it is, where should I put the portal code in?

**Comment by rrousselGit** [comment]
You can place your `Portal` above `MaterialApp`

**Comment by alihaider0026** [comment]
please give an example. If I want to show a portal on my home page above all then how I do this ?

**Comment by fzyzcjy** [comment]
@alihaider0026 Please see README and/or the example folder of this repo.

**Comment by fzyzcjy** [comment]
Close since there are already examples. Feel free to comment if you are still confused :)
