### ISSUE TITLE
Would be nice if a PortalEntry could self-contain it's own (always fullscreen) modal.

### ISSUE THREAD

**Issue by esDotDev** [fzyzcjy/flutter_portal#26]
The current approach of using 2 sibling Widgets is not condusive to standalone components. 

Commonly we want the same behavior for all ToolTips and inline popups which is a basic "showBarrier" and "barrierDismissable". 

The current approach requires you to add an Extra PortalEntry to every single view that uses tooltips, and re-write the same logic over and over, or create some extra architectural layer to smooth out this pain pt. It also forces you to maintain multiple bools to track multiple popups, rather than just letting each popup encapsulate it's own state. 

Would something like this be possible? 
```
StatefulPortalEntry(
            key: tipKey,
            barrierColor: Colors.black.withOpacity(.1);
            barrierDismissable: false,
            childAnchor: Alignment.bottomLeft,
            portalAnchor: Alignment.topLeft,
            child: ...
...
tipKey.currentState.visible = true;
```

The basic goal is, if I have a component, that has some popup menu (Like UserAvatar), and I have it exist in various views, I don't have to constantly change the surrounding view to have the popover work. I want to be able to plop a `UserAvatar` in place, and it works, I don't think this is possible currently.

**Comment by esDotDev** [comment]
Another pain point is when you have a Widget of a certain size like "TitleBar" that is 40px tall, and has some internal component that spawns a popover. You can not put the barrier Portal in Titlebar, cause it doesn't occupy  the full height of the screen. Maintaining the Titlebars open state inside the parent makes no sense and is messy. You could turn your Titlebar into a fullscreen stack, but that doesn't read well in terms of layout or scale well with a lot of components.

**Comment by esDotDev** [comment]
fwiw, I've started work on another approach that uses Notifications, I think it should turn out pretty cool.

At top of tree:
```
PopOverContext(child: ...)
```
Down the tree:
```
PopOverRegion(
  child: SomeButton();
  popChild: MyToolTip();
  anchor: Alignment.topRight,
  popAnchor: Alignment.topLeft,
  barrierDismissable: true,
  barrierColor: Colors.black.withOpacity(.05)
  mode: PopRegionMode.Hover,
)
```

Internally PopOverRegion just sends a `ShowPopOverNotification` up the tree, with a LayerLink and some settings.

Anyone can close the PopOvers anytime, by dispatching a `ClosePopOverNotification`. Which should make it really easy to have popovers can be shown from anywhere, and easily close themselves if they need.

Only describing in case it inspires some ideas. Cheers!

**Comment by fzyzcjy** [comment]
Sounds like this can be implemented without modifying the package code, such that the package can be minimal :) You approach seems quite good

**Comment by aytunch** [comment]
Hi @fzyzcjy and @esDotDev Do we have a `barrierDismissable` in Flutter Portal?
If not, what is the best way to implement it? If we use `anchor.filled` we can give a transparent background however we can't position the opaque menu in the desired location

**Comment by fzyzcjy** [comment]
I personally create a *second* portaltarget with fullscreen transparent-black content

**Comment by aytunch** [comment]
@fzyzcjy thanks for the quick reply. I tried the same solution and it works fine generally.
However, the full screen follower does not resize properly. When the browser window gets bigger, the full screen follower transparent-black background stays the same. (I am using anchor.filled)
Should I open a new issue for this or are you already aware of this problem?
