### ISSUE TITLE
Is it possible to position portal relative to window and not to child?

### ISSUE THREAD

**Issue by arualana** [fzyzcjy/flutter_portal#33]

**Comment by rrousselGit** [comment]
You can wrap the portal in a `Center`

**Comment by micodev** [comment]
@arualana  have you got any approach for that ?

**Comment by fzyzcjy** [comment]
Hi, https://github.com/rrousselGit/flutter_portal/pull/44 is merged. Could you please check whether this issue is resolved :)

**Comment by fzyzcjy** [comment]
Without further information, I will temporarily close this issue to make the issue tracker clean. Feel free to reopen (or create a new issue) if you are still facing problems after the https://github.com/fzyzcjy/flutter_portal/pull/44 refactor!
