### ISSUE TITLE
Error: Could not find a Portal above this PortalEntry(portalAnchor: Alignment.bottomCenter, childAnchor: Alignment.topCenter, closeDuration: null, portal: Text, child: TextField).

### ISSUE THREAD

**Issue by minh-dai** [fzyzcjy/flutter_portal#34]

**Comment by dan-gph** [comment]
Have you followed the directions in the documentation?:
> Before doing anything, you must insert the Portal widget in your widget tree. This widget enabled flutter_portal in your project.
> 
> You can place this Portal above MaterialApp or near the root of a route:
> ```
> Portal(
>   child: MaterialApp(
>     ...
>   )
> )
> ```

**Comment by minh-dai** [comment]
@dan-gph yes, i did

**Comment by tabacojt** [comment]
#29

**Comment by tabacojt** [comment]
> Have you followed the directions in the documentation?:
> 
> > Before doing anything, you must insert the Portal widget in your widget tree. This widget enabled flutter_portal in your project.
> > You can place this Portal above MaterialApp or near the root of a route:
> > ```
> > Portal(
> >   child: MaterialApp(
> >     ...
> >   )
> > )
> >

**Comment by fzyzcjy** [comment]
Could you please give a minimal reproducible sample? Sounds like you do not put a `Portal` up in the ancestors.

Closing this but feel free to reopen or recreate issue if you still face problems!
