### ISSUE TITLE
Interested in being a maintainer

### ISSUE THREAD

**Issue by tkfinitefield** [fzyzcjy/flutter_portal#38]
Hello, I am a Flutter developer and am interested in becoming a maintainer of this project.

**Comment by rrousselGit** [comment]
No problem!
Could you share your pub/github informations? I'll add you as uploader/maintainer

**Comment by tkfinitefield** [comment]
Thanks!
My pub domain name is finitefield.org and email is tk@finitefield.org
And my github name is tkfinitefield and email is tk@finitefield.org

**Comment by rrousselGit** [comment]
Sorry I forgot to check this issue, and in the meantime someone else expressed their interest (https://github.com/rrousselGit/flutter_portal/issues/40)

Do you think you could sync up with @fzyzcjy to decide what to do?

**Comment by fzyzcjy** [comment]
Hi, given the following comments:

> @tkfinitefield Because this project is not a big one, I feel it is tool costly and time-consuming to have several primary maintainers. So I would like to withdraw. Is this OK? https://github.com/fzyzcjy/flutter_portal/issues/40#issuecomment-1028493915

I guess maybe this issue can be closed. Feel free to reopen it if this still needs to be open!
