### ISSUE TITLE
Include package tests in `flutter/tests`

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [fzyzcjy/flutter_portal#46]
As proposed in https://github.com/flutter/flutter/issues/99349#issuecomment-1057202377 and in https://github.com/flutter/flutter/pull/92598#issuecomment-1029507750, I created a PR to add `flutter_portal` to https://github.com/flutter/tests/pull/126.

Looking at the existing tests for the package and the ones I added in #44, this should comply with all of the rules for `flutter/tests` (as defined in the README, see https://github.com/flutter/tests).

One concern there is is the fact that I added myself as the contact (see https://github.com/flutter/tests/pull/126/files#diff-b02b94965c78db569a2cf4abb644a108bdad643e5e1c664d1ac69a5aa21931d0R1).  
I **am** willing to follow-up on any requests to comply with breaking changes, however, I do not have _write access_ to this repo (cc @rrousselGit @fzyzcjy). We would either have to change that or (maybe preferably) include one of the two of you as the contact in `flutter/tests`.

**Comment by fzyzcjy** [comment]
Sounds great!

I can be a contact as well.

**Comment by creativecreatorormaybenot** [comment]
@fzyzcjy can you propose a change for that on the PR?

**Comment by creativecreatorormaybenot** [comment]
@fzyzcjy You can use GitHub PR review feature to suggest changes.
