### ISSUE TITLE
Missing migration guide

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [fzyzcjy/flutter_portal#52]
We need a migration to understand how to move from the old version of `flutter_portal` to the version with the `Anchor` refactor that was implemented in #44.

Assignee: @creativecreatorormaybenot

**Comment by fzyzcjy** [comment]
I will do that

**Comment by creativecreatorormaybenot** [comment]
@fzyzcjy I checked it and it roughly looks good to me. If you want me to look over all the adjustments you made and refine them in general, I can still do that but that would be at earliest next night.

That would also involve a more extensive migration guide :v:

**Comment by fzyzcjy** [comment]
@creativecreatorormaybenot Both OK for me :) I plan to release v1.0.0 this weekend
