### ISSUE TITLE
Portal follower with Filled anchor does not resize correctly when a surrounding Column changes height. [on master]

### ISSUE THREAD

**Issue by Quijx** [fzyzcjy/flutter_portal#53]
**Describe the bug**
When a `PortalTarget` is inside a `Column` (not with `Expanded` etc.), which is surrounded by the `Portal` and the `anchor` ist set to `Filled`, the `portalFollower` does not change its height to match the `Portal` if the `Portal` changes height. However it does update when the width is changed.

**To Reproduce**
- Create a new project `flutter create flutter_portal_bug`
- Add the following dependency in the `pubspec.yaml`
```yaml
  flutter_portal:
    git:
      url: https://github.com/rrousselGit/flutter_portal
      ref: 682cc5ef459dfeb8d102eecd9e2ddbb3252d984e
```
- Replace the `main.dart` with the following content:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_portal/flutter_portal.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'flutter_portal bug',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double width = 64;
  double height = 64;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Slider(
            value: width,
            min: 0,
            max: 512,
            onChanged: (v) => setState(() => width = v),
          ),
          Slider(
            value: height,
            min: 0,
            max: 512,
            onChanged: (v) => setState(() => height = v),
          ),
          Expanded(
            child: Center(
              child: SizedBox(
                width: width,
                height: height,
                child: Portal(
                  child: Container(
                    color: Colors.black,
                    child: Column(
                      children: [
                        PortalTarget(
                          portalFollower: Container(
                            color: Colors.blue.withOpacity(0.5),
                          ),
                          child: Container(
                            color: Colors.blueGrey,
                            width: 24,
                            height: 24,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```
- Run the App
- There are two sliders on the top. The upper one controlls the width of the `Portal`, and the lower one the height. The Portal has a black container as child which indicates the size of the `Portal`. The `portalFollower` is a semi transparent blue container.

**Expected behavior**
- The transparent blue container (`portalTarget`) always covers the black container (`Portal`) since the `anchor` is implicitly set to `Filled`

**Actual behavior**
- The transparent blue container (`portalTarget`) only changes its size to fit the black container (`Portal`) when the width is changed, but not when the height is changed.
- When the inner `Column` is remove, everything behaves as expected.

**Comment by fzyzcjy** [comment]
Thanks for the reproduction!

I guess, maybe we can print (log) the lifecycles of Portal/PortalTarget and have a look at it.

In addition, a workaround comes into my mind: Maybe create a widget, say, `ResizeThenRebuild`, which will `setState` on itself whenever it detects its size has changed. Then, the whole subtree (including portal) will rebuild, then the problem should resolve?

**Comment by Quijx** [comment]
I wrapped the `Portal` with a `LayoutBuilder`, which should to exactly that, since the builder is rerun every time the incoming constraints change. However that did not fix the bug. Likely because flutter sees that the widget types in the subtree have not changed and therefore reuses the elements. Only if you additionally give the `Portal` a `ValueKey` with the constraints from the `LayoutBuilder`, it works. However this should be avoided, since the entire `Element` and `RenderObject` subtrees needs to be rebuilt from scratch every frame the size changes.

That said however, I don't really need a workaround. I just stubled across this while trying to reproduce the exceptions I had in #13. But maybe this helps finding the root cause.

**Comment by fzyzcjy** [comment]
@Quijx Good point!

**Comment by TimWhiting** [comment]
Wrapping the Discovery in an Expanded or Flexible seems to solve the problem. It would be nice to find a permanent solution though.

**Comment by TimWhiting** [comment]
I saw there is a PR to get portal like functionality directly in flutter. Will this issue be solved there?

**Comment by fzyzcjy** [comment]
Not very sure, as the implementation is not exactly the same. Maybe need to ask there?

Or, e.g. contribute a test case there

**Comment by aytunch** [comment]
@Quijx could you find a solution for this unexpected behavior?

**Comment by Quijx** [comment]
@aytunch No, but I didn't really have this problem on any project of mine, but just stumbled across it while investigating something else. So I didn't try to find a workaround. Are you having the problem yourself and need a workaround?
