### ISSUE TITLE
Release v1.0.0-dev.1

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_portal#54]
Since there are some changes (https://github.com/rrousselGit/flutter_portal/blob/master/CHANGELOG.md), and the master branch works quite well for my 150kloc app in production, I guess it may be a good chance to release a new version later :)

Blocking issues

- [x] #49 
- [x] #52

**Comment by fzyzcjy** [comment]
Since this library is quite stable and has not had breaking change for a year (excluding #44), what about releasing v1.0 instead of v0.5?

**Comment by creativecreatorormaybenot** [comment]
@fzyzcjy That roughly sounds good to me. What I would propose is a **dev** / prerelease version first that we can use to see if the new abstraction really works with every use case and if so, release it as a stable version.

If we can wait, I would also add my refinement of the docs / migration guide / changes as a task 👍

**Comment by fzyzcjy** [comment]
@creativecreatorormaybenot 

> What I would propose is a dev / prerelease version first that we can use to see if the new abstraction really works with every use case and if so, release it as a stable version.

Good idea! 1.0.0-dev.1

> If we can wait, I would also add my refinement of the docs / migration guide / changes as a task 👍

I can wait to this weekend :)
