### ISSUE TITLE
'_debugCheckLeaderBeforeFollower(forwardLayers, inverseLayers)': LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_portal#57]
Digging out the issue now.

Have not reduce the real-world use case into a minimal reproducible sample yet.

```
`'package:flutter_portal/src/flutter_src/rendering_layer.dart': Failed assertion: line 365 pos 7: '_debugCheckLeaderBeforeFollower(forwardLayers, inverseLayers)': LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.`


flutter: [extra#0] bound_extra.0 => FlutterError.onError raw stackTrace=#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
flutter: #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
flutter: #2      CustomFollowerLayer._establishTransform (package:flutter_portal/src/flutter_src/rendering_layer.dart:365:7)
flutter: #3      CustomFollowerLayer.addToScene (package:flutter_portal/src/flutter_src/rendering_layer.dart:404:5)
flutter: #4      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:545:5)
flutter: #5      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1105:13)
flutter: #6      CustomLeaderLayer.addToScene (package:flutter_portal/src/flutter_src/rendering_layer.dart:140:5)
flutter: #7      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:545:5)
flutter: #8      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1105:13)
flutter: #9      CustomLeaderLayer.addToScene (package:flutter_portal/src/flutter_src/rendering_layer.dart:140:5)
flutter: #10     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:545:5)
flutter: #11     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1105:13)
flutter: #12     CustomLeaderLayer.addToScene (package:flutter_portal/src/flutter_src/rendering_layer.dart:140:5)
flutter: #13     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:545:5)
flutter: #14     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1105:13)

**Comment by fzyzcjy** [comment]
reproducible sample added

**Comment by fzyzcjy** [comment]
Cause: When a `PortalTarget` is in the `PortalTarget.portalFollower` subtree of another `PortalTarget`, the `Portal` bound by the first `PortalTarget` should be *lower* than the `Portal` bound by the second.

**Comment by Linkadi98** [comment]
I just find around and head to this issue when I try to make a portal target as a child of portal follower. I have made a context menu using this package and try to make a nested sub menu inside it, I try to use nested portal target as I mention before but it leads to this error. Is there any way to fix or make this happen? @fzyzcjy

**Comment by fzyzcjy** [comment]
@Linkadi98 what about my thoughts above:

> Cause: When a PortalTarget is in the PortalTarget.portalFollower subtree of another PortalTarget, the Portal bound by the first PortalTarget should be lower than the Portal bound by the second.

**Comment by Linkadi98** [comment]
I'm sorry but I don't understand this solution, can you give me a sample code? I have tried to wrap the nested PortalTarget in a Portal and the error is gone but the Portal now is limited by the area of the portalFollower

**Comment by fzyzcjy** [comment]
I forgot the details (it was too long ago), but I guess maybe it is allowed to have

```
Portal( // a
  child: Portal( // b
    child: PortalTarget( // point to portal a
      portalFollower: PortalTarget( // point to portal b
```

**Comment by Linkadi98** [comment]
Nice, I will try for now. I will let you know if it work in my case or not.

**Comment by Linkadi98** [comment]
Ok I make it. But to be clear, this issue should be mentioned in the doc for nested PortalTarget for future use. Thanks for your help.

**Comment by fzyzcjy** [comment]
Happy to see it is solved, and feel free to PR for doc (e.g. add a section, say, "Q&A" and mention this)!
