### ISSUE TITLE
`Aligned.backup` is always used even if it should not; cause: `getFollowerOffset`'s `portalRect` argument is wrong

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_portal#63]
root causes:

* #61 
* #62

**Comment by fzyzcjy** [comment]
## Very brief bug report

Bug that I have observed: `Aligned.backup` is always used even if it should not.

Direct cause: `getFollowerOffset`'s `portalRect` argument is wrong.

Root cause 1: As is mentioned in #61, the `applyPaintTransform` is wrong when using operations like `globalToLocal(ancestor: something)`; it only works correctly with `globalToLocal()` without ancestors param.

After fixing this bug, even more tests fail.

Root cause 2: `CustomRenderFollowerLayer._computeLinkedOffset` is wrong especially when having a RepaintBoundary at ancestor which is quite common.

**Comment by creativecreatorormaybenot** [comment]
Hi @fzyzcjy - I cannot quite follow your `ancestor` conclusion as it seems arbitrary based on the description. I noticed that you closed the issue(s); what was the reason for that?

I can try to help out here if you are having difficulties understanding the underlying framework logic.

**Comment by creativecreatorormaybenot** [comment]
Hi @fzyzcjy - I cannot quite follow your `ancestor` conclusion as it seems arbitrary based on the description. I noticed that you closed the issue(s); what was the reason for that?

I can try to help out here if you are having difficulties understanding the underlying framework logic (in case that help is still needed).

**Comment by fzyzcjy** [comment]
Hi @creativecreatorormaybenot - Thanks for your reply!

I have fixed this issue so I closed it, the bugfix can be seen in commit history.

**Comment by creativecreatorormaybenot** [comment]
@fzyzcjy It would be really helpful if you did not push to `main` directly and instead squash merged every change as a pull request. Can you link the commit in question?

**Comment by fzyzcjy** [comment]
@creativecreatorormaybenot

By the way, it is already fixed, so no worries about ti :)

https://github.com/fzyzcjy/flutter_portal/commits/master

The related code are partially marked #61 and #62. Next time I will squash such that they are easy to see.

![image](https://user-images.githubusercontent.com/5236035/160360792-d0235f47-6094-46c5-b06e-e2f565ba17f1.png)
