### ISSUE TITLE
`localToGlobal` or similar methods are wrong for widgets in the subtree of portal follower

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_portal#65]
fixing

**Comment by feduke-nukem** [comment]
It seems that the issue still persists.

During the initial call to the `paint` method of `RenderProxyBox`, there appears to be a slight discrepancy in the `Offset` obtained from the `localToGlobal` method and calls that were made later on the same position on the screen.

**Comment by fzyzcjy** [comment]
@feduke-nukem Hi, could you please provide a minimal reproducible sample (probably opening a new issue)? Then it will be easier to find the problem

**Comment by feduke-nukem** [comment]
> @feduke-nukem Hi, could you please provide a minimal reproducible sample (probably opening a new issue)? Then it will be easier to find the problem

https://github.com/fzyzcjy/flutter_portal/issues/105
