### ISSUE TITLE
[Question] Performance question

### ISSUE THREAD

**Issue by mtc-jed** [fzyzcjy/flutter_portal#72]
Hi,

I'd like to put an overlay that could be present throughout the whole app.
The user is uploading documents, and this overlay would provide a progress bar. It needs to stay visible no matter the screen the user is on.
Would wrapping my entire app with a PortalTarget cause performance issues ?

Thanks.

**Comment by fzyzcjy** [comment]
> Would wrapping my entire app with a PortalTarget cause performance issues ?

No issue. I do that personally and it is fine

**Comment by mtc-jed** [comment]
Perfect then, thanks for your time :)

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by mtc-jed** [comment]
@fzyzcjy How do you gain access to usable ancestor widgets such as MediaQuery when the whole app is wrapped in a PortalTarget ? Is there an example relevant to this somewhere ?
