### ISSUE TITLE
Global key error

### ISSUE THREAD

**Issue by adlion** [fzyzcjy/flutter_portal#73]
**Describe the bug**
Global key error

``` The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.
 The following GlobalKey was specified multiple times in the widget tree.
 This will lead to parts of the widget tree being truncated unexpectedly,
 because the second time a key is seen, the previous instance is moved to the new location. The key was:
 [LabeledGlobalKey<FormState>#e49bc]
```

**To Reproduce**

Tree structure is:
```MaterialApp(  
     child: Panel(
             child: SafeArea(
                     child:PortalTarget(
                            portalFollower:Container(color:Colors.green),
                           child: ---rest of widgets ----
            ),
        ),
    ),
)
```

 
If portal is shown and than you navigate to a new screen using Navigator is throwing the up-mentioned error.
I should mention also that I use riverpod to show or hide the portal(overlay).
Overlay is showing when application is requesting data from API and is being hidden when data are returned.
The error happens if back-end is returning an error that is being shown as overlay and than in 5 seconds is redirecting user to another screen with another overlay.
When is redirecting user to the new screen I should mention that the tree  I have shown here is being rebuild from Panel.
Have tried adding Panel as parent of MaterialApp and nothing changes.
I tired adding global key but without effect.

I suspect this error is due to the rebuild of the tree and it can not find the old PortalTarget.

This error does not happen if I hide the overlay before navigating to the other screen.

**Comment by adlion** [comment]
You are right.
I am reusing part of the tree while logging user out.

Please consider this issue closed.

Literally I was doing:

```
 child: Panel(
             child: SafeArea(
                     child:PortalTarget(
                            portalFollower:Container(color:Colors.green),
                           child: 
                           //While loggin out this par t was being added from authentication provider
                            Panel(
             child: SafeArea(
                     child:PortalTarget(
                            portalFollower:Container(color:Colors.green),
                           child: ---rest of widgets ----
                            ),
                        ),
                    ),
                )
            ),
        ),
    ),
)
```

Thank you for your quick reply and  support.
I was creating a sample for you and could not reproduce the error.
Than stripped down all my code to see where was the error and found out.

**Comment by fzyzcjy** [comment]
Happy to see you solved the problem :)
