### ISSUE TITLE
[Question] Can we make DraggableScrollableSheet overlay on top of bottom navigaton tabs?

### ISSUE THREAD

**Issue by mazino-dev** [fzyzcjy/flutter_portal#77]
**Describe what scenario you think is uncovered by the existing examples/articles**
Can we make DraggableScrollableSheet overlay on top of bottom navigaton tabs?

**Describe why existing examples/articles do not cover this case**
I looked at the menu, modal and discovery examples. I wish to position my overlay with respect to to root of the widget tree where portal widget was placed. I think current implmentation places overlay respect to target.

**Additional context**
My app has a bottom navbar. I have a button, when pressed it displays DraggableScrollableSheet. DraggableScrollableSheet does not behave like showModalBottomSheet() meaning it does not overlays on top of bottom nav bar but instead starts at bottom of widget its placed in. I want to use the library to make DraggableScrollableSheet overlay on top of app.

**Comment by fzyzcjy** [comment]
Customize the `anchor` logic and you can place a portalentry wherever you like.

**Comment by mazino-dev** [comment]
Oh will try it asap

**Comment by mazino-dev** [comment]
Got it working. Thanks man. BTW Your rust flutter bridge is pretty cool project, looking forward to try it.

```
PortalTarget(
      portalFollower: Positioned(
          bottom: 10,
          right: 10,
          child: Container(
            width: 100,
            height: 50,
            child: const Text(''),
            color: Colors.red,
          )),
      anchor: const Aligned(
        follower: Alignment.center,
        target: Alignment.center,
        portal: Alignment.bottomCenter,
        alignToPortal: AxisFlag(
          x: true,
          y: true,
        ),
      ),
      child: Container(
        width: 200,
        height: 100,
        child: const Text(''),
        color: Colors.amber,
      ),
    )
```

**Comment by fzyzcjy** [comment]
You are welcome! 😄
