### ISSUE TITLE
Portal makes ListView "freeze"

### ISSUE THREAD

**Issue by kissge** [fzyzcjy/flutter_portal#78]
**Describe the bug**
When using Portal together with ListView, the list scroll becomes choppy, and the scroll is blocked intermittently.

This problem occurs 100% under certain conditions:

1. The problem occurs either with Debug / profile / release build
2. Only tested with Web; not with iOS, Android, etc.
3. Mouse wheel scroll is blocked; scroll with PageDown key is not affected (smooth as expected)
4. Apparently if the window width is large enough, the problem won't occur

https://user-images.githubusercontent.com/4177010/166268174-0035fee2-fe5a-45c5-9b61-db04f1c85887.mov

Video: scroll is hindered with `_usePortal` = true. When switched to false, scroll becomes smooth.

It's not freezing the whole Flutter application, as can be observed by seeing `_counter` increasing.

**To Reproduce**

Repro is here: https://github.com/kissge/flutter_scroll
Relevant codes: https://github.com/kissge/flutter_scroll/commit/8908def700699978d639671951bb612ae4ea6d22

**Expected behavior**
Smooth scroll

Google Chrome 100.0.4896.127, Flutter 2.10.5, Dart 2.16.2, flutter_portal 1.0.0

If this is intended behavior, I'd much appreciate if you give me some hints for avoiding this problem.
(I'm just a newbie in Flutter, don't have basic knowledge like how to profile an app, etc.)

**Comment by fzyzcjy** [comment]
Sounds like a bug, and the bug report is detailed - great!

Could you please test on android/ios? I feel flutter web sometimes have strange bugs.
