### ISSUE TITLE
Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.

### ISSUE THREAD

**Issue by ValentinVignal** [fzyzcjy/flutter_portal#83]
**Describe the bug**

When running the tests, I get the warning:

```zsh
./../../.pub-cache/hosted/pub.dartlang.org/flutter_portal-1.1.0/lib/src/enhanced_composited_transform/flutter_src/rendering_layer.dart:51:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../flutter/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.addPostFrameCallback((Duration timeStamp) {
```

**To Reproduce**

I'm using flutter 3.0.5.

Run `flutter test` on :

```dart
// ignore: unused_import
import 'package:flutter_portal/flutter_portal.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {});
}
```

Or you can checkout https://github.com/ValentinVignal/flutter_app_stable/tree/portal/binding-warnings

**Expected behavior**

There should not be any compilation error

**Comment by fzyzcjy** [comment]
Maybe upgrade this package to latest version (1.x)?

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_portal/blob/166fb20a29555eb8f58a68fc0431d2fb6b83ab60/lib/src/enhanced_composited_transform/flutter_src/rendering_layer.dart#L51

Oops please use master branch

**Comment by ValentinVignal** [comment]
@fzyzcjy When are you planning to release a new version with this fix? It would be secure for us to use the master branch for our production app.

**Comment by fzyzcjy** [comment]
I will release it now

**Comment by fzyzcjy** [comment]
released
