### ISSUE TITLE
Enable offset data as a result of using `shiftToWithinBound` translation

### ISSUE THREAD

**Issue by mateoKutnjak** [fzyzcjy/flutter_portal#84]
Please enable access to `x` and `y` offset data when using `shiftToWithinBound: AxisFlag(x: true, y: true)`. Two variables should indicate how much is `PortalFollower` moved when translating it inside bounds of `Portal` parent.

This data needs to be accessed in `child` widget of `PortalFollower`

**Comment by fzyzcjy** [comment]
Notice the actual shift is calculated at a very late time, so it is impossible to get it at layout/build time...
