### ISSUE TITLE
PortalFollower hittest

### ISSUE THREAD

**Issue by jtdLab** [fzyzcjy/flutter_portal#93]
Hi i got the following situation

```dart
 SingleChildScrollView(
      child: Column(
        children: [
          // Some widgets
          PortalTarget(
            portalFollower: Follower(),
            child: Child(),
          ),
          // Some more widgets
        ],
      ),
    );
```

where `Follower` is a widget that has children that should be clickable like buttons or smth.

The problem is if `Follower` gets hovered its not possible to scroll anymore.
To fix that i tried to wrap `Follower` with a `IgnorePointer` widget then the scrolling works but the children that should be clickable are failing hittesting and thus cant be clicked.

Is there a solution to that problem where on hover scrolling works but also children can be clicked?

**Comment by fzyzcjy** [comment]
Hmm maybe do not wrap in portalfollower?

**Comment by jtdLab** [comment]
Oh sorry i forgot to mention the whole thing is wrapped by `MaterialApp` wich is wrapped with `Portal` above.
