### ISSUE TITLE
In the example contextual_menu, menu does not hide when click randomly outside of the menu.

### ISSUE THREAD

**Issue by mrbeardad** [fzyzcjy/flutter_portal#99]
**Describe the bug**
In the example [contextual_menu](https://github.com/fzyzcjy/flutter_portal/blob/master/example/lib/contextual_menu.dart), menu does not hide when click randomly outside of the menu.

**To Reproduce**

1. Run the code on Windows10
2. Click the button then show the menu
3. Click the space outside of the menu, the menu doesn't hide.
![image](https://user-images.githubusercontent.com/54128430/216761518-90bed8f7-37b2-44fc-8f96-32594f2016ef.png)

**Expected behavior**
When the context menu is visible, it should hide when I click randomly outside of the menu.

**Comment by fzyzcjy** [comment]
Yes. In order to have that, you should have another PortalTarget which is (for example) a fullscreen container, and listen to onTap of that, and close your menu when you get tap

**Comment by mrbeardad** [comment]
Ohh. So how to generate a fullscreen transparent widgets that below the menu? I've tried following code but the menu can't receive onTap event.
```dart
  @override
  Widget build(BuildContext context) {
    return PortalTarget(
      visible: visible,
      portalFollower: PortalTarget(
        visible: visible,
        portalFollower: GestureDetector(
          behavior: HitTestBehavior.translucent,
          onTap: onClose,
        ),
        child: menu,
      ),
      anchor: const Aligned(
        follower: Alignment.topLeft,
        target: Alignment.bottomLeft,
        widthFactor: 1,
        backup: Aligned(
          follower: Alignment.bottomLeft,
          target: Alignment.topLeft,
          widthFactor: 1,
        ),
      ),
      child: child,
    );
  }
```

**Comment by fzyzcjy** [comment]
You may use standard debugging tricks to fix it. 

Without debugging, I guess you can make GestureDetector have a child Container with color transparent

**Comment by d9media** [comment]
Hi @mrbeardad, i hope you found a solution. I came across the same issue and solved it with the approach described in the Modal example: https://github.com/fzyzcjy/flutter_portal/blob/master/example/lib/modal.dart. Basically, you wrap your portal target in the barrier widget as such

`Barrier(
      visible: isMenuOpen,
      onClose: () => setState(() => isMenuOpen = false),
     child: // your PortalTarget
)`

**Comment by alguintu** [comment]
> ```
> Barrier(
>       visible: isMenuOpen,
>       onClose: () => setState(() => isMenuOpen = false),
>      child: // your PortalTarget
> )
> ```

Thanks @mrbeardad, I was wracking my head as the docs wasn't very clear about it. I also found that using Listener + onPointerDown instead of GestureDetector+onTap in the Barrier code results to better user experience as any gesture outside the Overlay hides it instead of an actual tap.
